### ISSUE TITLE
Delete image option

### ISSUE THREAD

**Issue by bwrsandman** [McCzarny/upload-image#3]
It would be useful to add an option to delete an image using the response delete url.

**Comment by rvalitov** [comment]
It's a good idea. One of the scenarios I have in mind for this: I have a workflow that automatically builds the project's web pages and uploads screenshots of the rendered pages to PR to make sure that visually the vital pages are looking good. If the PR is merged, it would be nice to delete the images as they are not needed anymore. The expiration option #7 can be used in this case as an alternative solution. However, sometimes a complicated PR can be in draft state for months till all the issues are fixed, so expiration option may not be an optimal solution in such a case...

**Comment by rvalitov** [comment]
@McCzarny I've been actively using your action in my workflows! Thank you! It works great and allows to automatically post screenshots of different tests as comments in PRs. This is an example:

![image](https://github.com/user-attachments/assets/d0e379cf-8963-4c63-b78b-aa2d5c9b54a2)

However, now I face a problem that the free tariff plan of imgbb is not enough for me. I'm not planning to buy a subscription, as I was thinking only of using it for temporary image storage during the PRs so I should not go beyond the free limit of 32 Mb. However, even if I specify a short auto-delete option for the uploaded images like 7 days, it's not enough to keep my space clean and fit into the 32Mb limit.

If this feature of deleting uploaded images would be implemented, I think it solve my problem. The idea is that every time a GitHub workflow starts in PR it checks if any images have already been uploaded to Imgbb, and if yes, it deletes them first. After that it makes new screenshots and uploades them to Imgbb. And a dedicated job is launched when PR is merged to delete the images. I plan to use artifacts to store information about the uploaded images with their delete URLs that would allow me to implement the logic above. What do you think? Is it a good approach or perhaps you have some better ideas?

**Comment by McCzarny** [comment]
As far as I can remember, the IMGBB API returns a URL to delete an image (haven't tried it yet). Probably a simple HTTP request will do, if so adding a new action output should do the trick. 
I will test it over the Christmas break ;)

**Comment by McCzarny** [comment]
It turned out that the returned delete URL is not something that can be used with a REST API call. It's possible to remove the image with clicking the button on the returned URL or there is also an undocumented POST request that removes the image using information from the delete url.
I'm considering creation of a separate action to remove imgbb image based on the delete url.

You can check the changes in the PR #22 There is a test using the undocumented call. I will try to add an example of a workflow where the image is deleted using the returned URL.

**Comment by rvalitov** [comment]
Thank you! I'm happy to see this PR! Sorry, don't have time to run this code, I did only read it, and it looks good to me!

If you will make a separate action to delete images (that's awesome) then I would be happy to see the following functionality:

- parameter to pass a list of `urls` to delete received from this action
- parameter to specify a `json` file with the `urls` to delete
- parameter `zipFilename` to specify a `zip` file with `json` file inside specified by parameter `jsonFilename`. This `json` file contains the `urls` to delete. This is the most important thing here, because the plan is to store the `urls` as artifacts (that is in fact a `zip` file) and delete them later. It's easy to use existing actions in marketplace to save and retrieve the artifacts as a `zip`, so it would be fantastic if your new action could process these artifacts as input parameter.

Also I think it would be great if in this PR you would add a new optional input parameter `jsonFilename` to specify a `json` file where this action will save the `delete urls`. Then I could pass this file directly to save as artifact!

**Comment by McCzarny** [comment]
The new output introduced with #22
